### ISSUE TITLE
Neat ideas pile

### ISSUE THREAD

**Issue by foolswood** [foolswood/rage#38]
- [ ] Oversampled sections
- [ ] Different sample depth sections
- [ ] N band eq
- [ ] LV2 element
- [ ] Timeseries to represent flow of time for another
- [ ] Plugin state "checkpoints"

**Comment by ch3pjw** [comment]
Moved to separate issues on GitLab:
 * [Oversampled sections](https://gitlab.com/concert/rage/issues/7)
 * [Different sample depth sections](https://gitlab.com/concert/rage/issues/8)
 * [N band eq](https://gitlab.com/concert/rage/issues/9)
 * [LV2 element](https://gitlab.com/concert/rage/issues/3)
 * [Timeseries to represent flow of time for another](https://gitlab.com/concert/rage/issues/12)
 * [Plugin state "checkpoints"](https://gitlab.com/concert/rage/issues/10)
